.PHONY: clean All

All:
	@echo "----------Building project:[ PECLSanzDelOlmoHector - Debug ]----------"
	@cd "PECLSanzDelOlmoHector" && "$(MAKE)" -f  "PECLSanzDelOlmoHector.mk"
clean:
	@echo "----------Cleaning project:[ PECLSanzDelOlmoHector - Debug ]----------"
	@cd "PECLSanzDelOlmoHector" && "$(MAKE)" -f  "PECLSanzDelOlmoHector.mk" clean
