.PHONY: clean All

All:
	@echo "----------Building project:[ ejemplo01 - Debug ]----------"
	@cd "ejemplo01" && "$(MAKE)" -f  "ejemplo01.mk"
clean:
	@echo "----------Cleaning project:[ ejemplo01 - Debug ]----------"
	@cd "ejemplo01" && "$(MAKE)" -f  "ejemplo01.mk" clean
