.PHONY: clean All

All:
	@echo "----------Building project:[ ejemploCola - Debug ]----------"
	@cd "ejemploCola" && "$(MAKE)" -f  "ejemploCola.mk"
clean:
	@echo "----------Cleaning project:[ ejemploCola - Debug ]----------"
	@cd "ejemploCola" && "$(MAKE)" -f  "ejemploCola.mk" clean
